# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: build go
    cmds:
      - env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o ../../.dist/place-bet/main main.go
      - chmod +x ../../.dist/place-bet/main
      - cd ../../.dist/place-bet && zip main.zip main
    sources:
      - ./*.go
      - main/*.go
      - Taskfile.yml
    generates:
      - ../../.dist/place-bet/main
    silent: true
